import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function CreditsScreen() {
  const colors = useColors();
  const packs = [{ label: "Starter", credits: "10 credits", price: "$9" }, { label: "Growth", credits: "50 credits", price: "$35" }, { label: "Scale", credits: "150 credits", price: "$89" }];
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5 pt-3" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: colors.primary }]}>USAGE CAPACITY</Text><Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>Buy credits when you need them.</Text><Text style={[styles.copy, { color: colors.muted }]}>Credits are designed for metered optimization actions. In production, purchases are verified server-side before entitlements are granted.</Text><View style={[styles.balance, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.label, { color: colors.muted }]}>CURRENT BALANCE</Text><Text style={[styles.value, { color: colors.foreground }]}>3 credits</Text><Text style={[styles.note, { color: colors.muted }]}>Free plan · resets monthly</Text></View>{packs.map((pack) => <View key={pack.label} style={[styles.pack, { backgroundColor: colors.surface, borderColor: colors.border }]}><View><Text style={[styles.name, { color: colors.foreground }]}>{pack.label}</Text><Text style={[styles.credits, { color: colors.primary }]}>{pack.credits}</Text></View><View style={styles.right}><Text style={[styles.price, { color: colors.foreground }]}>{pack.price}</Text><Pressable accessibilityRole="button" onPress={() => Alert.alert("Purchase handoff", "Store purchase and receipt verification are not connected in demo mode.")} style={({ pressed }) => [styles.buy, { backgroundColor: colors.primary }, pressed && styles.pressed]}><Text style={[styles.buyText, { color: colors.background }]}>Buy</Text></Pressable></View></View>)}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 13 }, eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800", marginTop: 4 }, title: { fontSize: 29, lineHeight: 34, fontWeight: "800" }, copy: { fontSize: 14, lineHeight: 21 }, balance: { borderRadius: 18, borderWidth: 1, padding: 17, marginTop: 4 }, label: { fontSize: 10, fontWeight: "800", letterSpacing: 1 }, value: { fontSize: 29, fontWeight: "800", marginTop: 7 }, note: { fontSize: 12, marginTop: 4 }, pack: { borderRadius: 16, borderWidth: 1, padding: 15, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, name: { fontSize: 16, fontWeight: "800" }, credits: { fontSize: 13, fontWeight: "700", marginTop: 6 }, right: { alignItems: "flex-end" }, price: { fontSize: 17, fontWeight: "800" }, buy: { minWidth: 70, minHeight: 38, borderRadius: 10, alignItems: "center", justifyContent: "center", marginTop: 8 }, buyText: { fontSize: 13, fontWeight: "800" }, pressed: { opacity: .78 } });
