import { router } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function UpgradeScreen() {
  const colors = useColors();
  const plans = [{ name: "Pro", price: "$19 / month", copy: "50 experiments, analytics, and report exports.", featured: true }, { name: "Business", price: "$99 / month", copy: "Team workspaces, shared projects, and advanced controls.", featured: false }];
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5 pt-3" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: colors.primary }]}>PLANS</Text><Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>Make more decisions with confidence.</Text><Text style={[styles.copy, { color: colors.muted }]}>Choose the capacity that fits your operation. Billing verification belongs on the secure backend in production.</Text>{plans.map((plan) => <View key={plan.name} style={[styles.card, { backgroundColor: colors.surface, borderColor: plan.featured ? colors.primary : colors.border }]}><View style={styles.top}><Text style={[styles.name, { color: colors.foreground }]}>{plan.name}</Text>{plan.featured && <Text style={[styles.badge, { color: colors.primary }]}>POPULAR</Text>}</View><Text style={[styles.price, { color: colors.foreground }]}>{plan.price}</Text><Text style={[styles.planCopy, { color: colors.muted }]}>{plan.copy}</Text><Pressable accessibilityRole="button" onPress={() => Alert.alert("Checkout handoff", "Native store checkout and server-side receipt verification will be connected here in production.")} style={({ pressed }) => [styles.button, { backgroundColor: plan.featured ? colors.primary : colors.background, borderColor: colors.primary }, pressed && styles.pressed]}><Text style={[styles.buttonText, { color: plan.featured ? colors.background : colors.primary }]}>Choose {plan.name}</Text></Pressable></View>)}<Pressable accessibilityRole="button" onPress={() => router.push("/credits")}><Text style={[styles.link, { color: colors.primary }]}>Prefer usage-based capacity? Buy credits</Text></Pressable></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 14 }, eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800", marginTop: 4 }, title: { fontSize: 29, lineHeight: 34, fontWeight: "800" }, copy: { fontSize: 14, lineHeight: 21 }, card: { borderRadius: 18, borderWidth: 1, padding: 17, marginTop: 5 }, top: { flexDirection: "row", justifyContent: "space-between" }, name: { fontSize: 20, fontWeight: "800" }, badge: { fontSize: 10, fontWeight: "800", letterSpacing: 1 }, price: { fontSize: 25, fontWeight: "800", marginTop: 12 }, planCopy: { fontSize: 13, lineHeight: 19, marginTop: 5 }, button: { minHeight: 49, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center", marginTop: 15 }, buttonText: { fontSize: 14, fontWeight: "800" }, link: { textAlign: "center", fontSize: 13, fontWeight: "800", paddingVertical: 6 }, pressed: { opacity: .78 } });
