import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

const areas = [{ label: "Tasks", detail: "4 due today", route: "/business/tasks" }, { label: "Orders", detail: "2 awaiting review", route: "/business/orders" }, { label: "Inventory", detail: "3 items to reorder", route: "/business/inventory" }, { label: "Team", detail: "8 active members", route: "/business/team" }, { label: "Customers", detail: "24 contacts", route: "/business/customers" }, { label: "Notifications", detail: "3 unread updates", route: "/business/notifications" }];

export default function BusinessHub() { const colors = useColors(); return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5 pt-3" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: colors.primary }]}>OPERATIONS</Text><Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>Business workspace</Text><Text style={[styles.copy, { color: colors.muted }]}>Keep the daily work moving, then use QuantumROI when a decision needs deeper optimization.</Text><View style={[styles.banner, { backgroundColor: colors.primary + "16", borderColor: colors.primary + "55" }]}><Text style={[styles.bannerTitle, { color: colors.foreground }]}>Today’s focus</Text><Text style={[styles.bannerCopy, { color: colors.muted }]}>Review urgent tasks and confirm the two orders waiting on approval.</Text></View><View style={styles.grid}>{areas.map((area) => <Pressable key={area.label} accessibilityRole="button" accessibilityLabel={`Open ${area.label}`} onPress={() => router.push({ pathname: "/business/[section]", params: { section: area.label.toLowerCase() } })} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: colors.primary + "18" }]}><Text style={[styles.iconText, { color: colors.primary }]}>{area.label.slice(0, 1)}</Text></View><Text style={[styles.label, { color: colors.foreground }]}>{area.label}</Text><Text style={[styles.detail, { color: colors.muted }]}>{area.detail}</Text></Pressable>)}</View><Pressable accessibilityRole="button" onPress={() => router.push("/optimize")} style={({ pressed }) => [styles.optimize, { backgroundColor: colors.primary }, pressed && styles.pressed]}><Text style={[styles.optimizeTitle, { color: colors.background }]}>Optimize an operational decision</Text><Text style={[styles.optimizeCopy, { color: colors.background }]}>Start with delivery routes and compare strategies.</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 14 }, eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800", marginTop: 4 }, title: { fontSize: 29, fontWeight: "800" }, copy: { fontSize: 14, lineHeight: 21 }, banner: { borderRadius: 16, borderWidth: 1, padding: 14, marginTop: 3 }, bannerTitle: { fontSize: 14, fontWeight: "800" }, bannerCopy: { fontSize: 13, lineHeight: 19, marginTop: 5 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, card: { width: "48%", minHeight: 126, borderRadius: 16, borderWidth: 1, padding: 14 }, icon: { width: 32, height: 32, borderRadius: 10, alignItems: "center", justifyContent: "center" }, iconText: { fontWeight: "800", fontSize: 15 }, label: { fontSize: 15, fontWeight: "800", marginTop: 12 }, detail: { fontSize: 12, marginTop: 5 }, optimize: { borderRadius: 17, padding: 16, marginTop: 2 }, optimizeTitle: { fontSize: 16, fontWeight: "800" }, optimizeCopy: { fontSize: 12, marginTop: 5, opacity: .82 }, pressed: { opacity: .78, transform: [{ scale: .99 }] } });
