import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

const backends = [{ id: "sim", name: "Local simulator", provider: "QuantumROI", qubits: "12 qubits", state: "AVAILABLE", simulation: true }, { id: "ibm", name: "IBM Quantum adapter", provider: "Server connection", qubits: "Provider-dependent", state: "CONFIGURE", simulation: false }, { id: "aws", name: "Amazon Braket adapter", provider: "Server connection", qubits: "Provider-dependent", state: "CONFIGURE", simulation: false }];

export default function QuantumBackendsScreen() { const colors = useColors(); const [selected, setSelected] = useState("sim"); return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5 pt-3" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: colors.primary }]}>QUANTUM TOOLS</Text><Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>Backends</Text><Text style={[styles.copy, { color: colors.muted }]}>Choose an execution target. Provider credentials remain server-side and are never placed in the mobile bundle.</Text>{backends.map((backend) => <Pressable key={backend.id} accessibilityRole="button" accessibilityState={{ selected: selected === backend.id }} onPress={() => setSelected(backend.id)} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: selected === backend.id ? colors.primary : colors.border }, pressed && styles.pressed]}><View style={styles.top}><View style={styles.nameWrap}><Text style={[styles.name, { color: colors.foreground }]}>{backend.name}</Text><Text style={[styles.meta, { color: colors.muted }]}>{backend.provider} · {backend.qubits}</Text></View><View style={[styles.dot, { backgroundColor: backend.state === "AVAILABLE" ? colors.success : colors.warning }]} /></View><View style={styles.bottom}><Text style={[styles.state, { color: backend.state === "AVAILABLE" ? colors.success : colors.warning }]}>{backend.state}</Text><Text style={[styles.mode, { color: colors.muted }]}>{backend.simulation ? "SIMULATION" : "HARDWARE ADAPTER"}</Text></View></Pressable>)}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30, gap: 13 }, eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800", marginTop: 4 }, title: { fontSize: 29, fontWeight: "800" }, copy: { fontSize: 14, lineHeight: 21 }, card: { borderRadius: 17, borderWidth: 1, padding: 15 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, nameWrap: { flex: 1 }, name: { fontSize: 16, fontWeight: "800" }, meta: { fontSize: 12, marginTop: 5 }, dot: { width: 10, height: 10, borderRadius: 5 }, bottom: { flexDirection: "row", justifyContent: "space-between", marginTop: 14 }, state: { fontSize: 10, letterSpacing: 1, fontWeight: "800" }, mode: { fontSize: 10, letterSpacing: .7, fontWeight: "700" }, pressed: { opacity: .78 } });
