import React, { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ui, toneColor, Tone } from '../theme';
import { ConstraintStatus, CostLine, EvidenceItem, KPIHealth, TrendPoint, clamp01, formatPercent, formatUSDmillions, statusTone } from '../data/mockAnalytics';
import { Body, Button, DataRow, Eyebrow, Pill, Progress, Section, Sparkline, Surface, TinyBarChart, Title } from './ui';

export function SearchField({ placeholder='Search', onChange }: {placeholder?:string;onChange?:(value:string)=>void}) { return <View style={styles.search}><Text style={styles.searchGlyph}>⌕</Text><TextInput accessibilityLabel={placeholder} placeholder={placeholder} placeholderTextColor={ui.colors.text3} onChangeText={onChange} style={styles.searchInput}/><Text style={styles.searchHint}>⌘K</Text></View>; }

export function StatusBadge({ status }: {status:string}) { const tone=statusTone(status); return <Pill label={status.toUpperCase()} tone={tone}/>; }

export function KPIHealthGrid({ items }: {items:KPIHealth[]}) { return <View style={styles.kpiGrid}>{items.map(item=><Surface key={item.label} style={styles.kpiHealth}><View style={styles.row}><Eyebrow tone={item.tone}>{item.label}</Eyebrow><View style={[styles.healthDot,{backgroundColor:toneColor(item.tone)}]}/></View><Text style={styles.kpiHealthValue}>{item.value}</Text><Text style={styles.kpiHealthDetail}>{item.detail}</Text></Surface>)}</View>; }

export function ComparisonCard({ title, baseline, optimized, unit='%', direction='lower', detail }: {title:string;baseline:number;optimized:number;unit?:string;direction?:'lower'|'higher';detail?:string}) { const delta=optimized-baseline; const improvement=baseline===0?0:Math.abs(delta/baseline)*100; const good=direction==='lower'?optimized<baseline:optimized>baseline; return <Surface style={styles.compare}><View style={styles.row}><View style={{flex:1}}><Eyebrow tone="neutral">{title}</Eyebrow><Text style={styles.compareDetail}>{detail}</Text></View><Text style={[styles.compareDelta,{color:good?ui.colors.green:ui.colors.amber}]}>{good?'Improved':'Changed'} · {improvement.toFixed(1)}%</Text></View><View style={styles.compareValues}><View><Text style={styles.smallLabel}>BASELINE</Text><Text style={styles.compareValue}>{unit==='$'?formatUSDmillions(baseline):`${baseline}${unit}`}</Text></View><Text style={styles.arrow}>→</Text><View><Text style={styles.smallLabel}>OPTIMIZED</Text><Text style={[styles.compareValue,{color:good?ui.colors.green:ui.colors.cyan}]}>{unit==='$'?formatUSDmillions(optimized):`${optimized}${unit}`}</Text></View></View></Surface>; }

export function TrendPanel({ title, subtitle, series, tone='blue', unit='' }: {title:string;subtitle:string;series:TrendPoint[];tone?:Tone;unit?:string}) { return <Surface><Section title={title} subtitle={subtitle}/><View style={styles.trend}><TinyBarChart values={series.map(x=>x.value)} labels={series.map(x=>x.label)} tone={tone}/></View><View style={styles.trendFooter}><Text style={styles.trendLast}>{series.at(-1)?.value.toFixed(1)}{unit}</Text><Text style={styles.trendNote}>latest</Text><Text style={styles.trendDelta}>{trendDelta(series).toFixed(1)}% vs first period</Text></View></Surface>; }
function trendDelta(series:TrendPoint[]){const first=series[0]?.value??0;const last=series.at(-1)?.value??0;return first===0?0:((last-first)/Math.abs(first))*100;}

export function DriverBars({ title, subtitle, lines, max=100 }: {title:string;subtitle?:string;lines:CostLine[];max?:number}) { return <Surface><Section title={title} subtitle={subtitle}/>{lines.map(line=><View key={line.label} style={styles.driver}><View style={styles.driverHead}><Text style={styles.driverLabel}>{line.label}</Text><Text style={styles.driverValue}>{line.value}%</Text></View><Progress value={line.value/max} tone={line.tone}/></View>)}</Surface>; }

export function ConstraintTable({ rows }: {rows:ConstraintStatus[]}) { return <Surface><Section title="Constraint inspector" subtitle="Business rules remain visible before and after optimization."/>{rows.map(row=><View key={row.id} style={styles.constraintRow}><View style={{flex:1}}><Text style={styles.constraintTitle}>{row.label}</Text><Text style={styles.constraintDetail}>{row.detail}</Text></View><View style={styles.constraintRight}><Pill label={row.type.toUpperCase()} tone={row.type==='hard'?'red':'amber'}/><Progress value={row.utilization} right={formatPercent(row.utilization)} tone={row.status==='watch'?'amber':'green'}/></View></View>)}</Surface>; }

export function EvidenceChain({ items }: {items:EvidenceItem[]}) { return <Surface><Section title="Evidence chain" subtitle="Every decision can point to a concrete artifact."/>{items.map((item,index)=><View key={item.id} style={styles.evidenceRow}><View style={[styles.evidenceLine,{backgroundColor:index<items.length-1?ui.colors.line: 'transparent'}]}/><View style={[styles.evidenceIcon,{borderColor:item.status==='pending'?ui.colors.amber:ui.colors.green,backgroundColor:item.status==='pending'?'#2D2817':'#0B2722'}]}><Text style={{color:item.status==='pending'?ui.colors.amber:ui.colors.green,fontSize:10,fontWeight:'900'}}>{item.status==='pending'?'!':'✓'}</Text></View><View style={{flex:1}}><Text style={styles.evidenceTitle}>{item.title}</Text><Text style={styles.evidenceSource}>{item.source} · {item.updated}</Text><Text style={styles.evidenceHash}>{item.hash}</Text></View><StatusBadge status={item.status}/></View>)}</Surface>; }

export function AssumptionTable({ rows }: {rows:Array<{label:string;value:string;range:string;impact:number}>}) { const [expanded,setExpanded]=useState<string|null>(null); return <Surface><Section title="Assumptions" subtitle="Tap any row to inspect the range and modeled impact."/>{rows.map(row=>{const open=expanded===row.label;return <Pressable key={row.label} onPress={()=>setExpanded(open?null:row.label)} style={styles.assumption}><View style={styles.row}><Text style={styles.assumptionLabel}>{row.label}</Text><Text style={styles.assumptionValue}>{row.value}</Text></View><View style={styles.assumptionMeta}><Text style={styles.assumptionRange}>{row.range}</Text><Text style={styles.assumptionImpact}>{row.impact}% impact</Text></View>{open&&<View style={styles.assumptionOpen}><Progress value={row.impact/50} tone="violet"/><Text style={styles.assumptionOpenText}>This is synthetic demonstration data. Validate the parameter against operational measurements before using it for planning.</Text></View>}</Pressable>})}</Surface>; }

export function Waterfall({ items }: {items:Array<{label:string;value:number;tone:Tone}>}) { const max=Math.max(...items.map(i=>Math.abs(i.value)),1); return <Surface><Section title="Value waterfall" subtitle="Illustrative bridge from baseline to modeled net value."/><View style={styles.waterfall}>{items.map((item,index)=><View key={item.label} style={styles.waterCol}><View style={styles.waterTrack}><View style={[styles.waterBar,{height:`${Math.max(8,Math.abs(item.value)/max*78)}%`,backgroundColor:toneColor(item.tone)}]} /></View><Text style={styles.waterLabel}>{item.label}</Text><Text style={styles.waterValue}>{item.value>=0?'+':''}{formatUSDmillions(item.value)}</Text></View>)}</View></Surface>; }

export function TrustBanner({ title, detail, tone='green' }: {title:string;detail:string;tone?:Tone}) { return <Surface tone={tone==='green'?'success':'warning'} style={styles.trust}><View style={[styles.trustIcon,{backgroundColor:toneColor(tone)}]}><Text style={{color:ui.colors.canvas,fontWeight:'900'}}>✓</Text></View><View style={{flex:1}}><Text style={styles.trustTitle}>{title}</Text><Text style={styles.trustDetail}>{detail}</Text></View></Surface>; }

export function ReportPreview({ title, period, value, cases, experiments, onOpen }: {title:string;period:string;value:number;cases:number;experiments:number;onOpen:()=>void}) { return <Surface style={styles.report}><View style={styles.row}><Pill label="REPORT" tone="blue"/><StatusBadge status="Ready"/></View><Title size="section">{title}</Title><Body>{period} · synthesized from the current experiment portfolio.</Body><View style={styles.reportKpi}><View><Text style={styles.smallLabel}>MODELED VALUE</Text><Text style={styles.reportValue}>${value.toFixed(1)}M</Text></View><View><Text style={styles.smallLabel}>CASES</Text><Text style={styles.reportKpiValue}>{cases}</Text></View><View><Text style={styles.smallLabel}>EXPERIMENTS</Text><Text style={styles.reportKpiValue}>{experiments}</Text></View></View><Button title="Open report" kind="secondary" onPress={onOpen}/></Surface>; }

export function MiniSparkMetric({ label, value, trend, series, tone='cyan' }: {label:string;value:string;trend:string;series:number[];tone?:Tone}) { return <Surface style={styles.miniSpark}><Eyebrow tone="neutral">{label}</Eyebrow><View style={styles.row}><Text style={styles.miniValue}>{value}</Text><Text style={[styles.miniTrend,{color:toneColor(tone)}]}>{trend}</Text></View><Sparkline values={series} tone={tone}/></Surface>; }

export function PaginationStub({ page, pages, onChange }: {page:number;pages:number;onChange:(page:number)=>void}) { return <View style={styles.pagination}><Button title="‹" kind="secondary" onPress={()=>onChange(Math.max(1,page-1))}/><Text style={styles.pageText}>Page {page} of {pages}</Text><Button title="›" kind="secondary" onPress={()=>onChange(Math.min(pages,page+1))}/></View>; }

export function FilterBar({ value, onChange, options }: {value:string;onChange:(v:string)=>void;options:string[]}) { return <View style={styles.filterBar}>{options.map(option=><Pressable key={option} onPress={()=>onChange(option)} style={[styles.filter,{backgroundColor:value===option?ui.colors.text:ui.colors.surface,borderColor:value===option?ui.colors.text:ui.colors.line}]}><Text style={[styles.filterText,{color:value===option?ui.colors.canvas:ui.colors.text3}]}>{option}</Text></Pressable>)}</View>; }

export function ScoreGauge({ label, score, caption, tone='violet' }: {label:string;score:number;caption:string;tone?:Tone}) { const pct=clamp01(score); return <Surface style={styles.gauge}><View><Eyebrow tone={tone}>{label}</Eyebrow><Text style={styles.gaugeScore}>{Math.round(pct*100)}</Text><Text style={styles.gaugeCaption}>{caption}</Text></View><View style={styles.gaugeRing}><View style={[styles.gaugeArc,{height:`${pct*100}%`,backgroundColor:toneColor(tone)}]}/></View></Surface>; }

const styles=StyleSheet.create({
 search:{height:42,borderWidth:1,borderColor:ui.colors.line,borderRadius:13,backgroundColor:ui.colors.surface,flexDirection:'row',alignItems:'center',paddingHorizontal:11,gap:7},searchGlyph:{color:ui.colors.text3,fontSize:19},searchInput:{flex:1,color:ui.colors.text,fontSize:12,paddingVertical:0},searchHint:{color:ui.colors.text3,fontSize:8,fontWeight:'900'},
 row:{flexDirection:'row',alignItems:'center',gap:9},kpiGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},kpiHealth:{flex:1,minWidth:190,padding:14},healthDot:{width:7,height:7,borderRadius:7},kpiHealthValue:{color:ui.colors.text,fontSize:21,fontWeight:'900',marginTop:5},kpiHealthDetail:{color:ui.colors.text3,fontSize:9,lineHeight:14,marginTop:2},
 compare:{gap:11},compareDetail:{color:ui.colors.text3,fontSize:9,marginTop:2},compareDelta:{fontSize:9,fontWeight:'900'},compareValues:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},smallLabel:{color:ui.colors.text3,fontSize:8,fontWeight:'900'},compareValue:{color:ui.colors.text,fontSize:22,fontWeight:'900',marginTop:3},arrow:{color:ui.colors.text3,fontSize:18},trend:{marginTop:4},trendFooter:{flexDirection:'row',alignItems:'baseline',gap:7},trendLast:{color:ui.colors.text,fontSize:17,fontWeight:'900'},trendNote:{color:ui.colors.text3,fontSize:8},trendDelta:{color:ui.colors.green,fontSize:9,fontWeight:'800',marginLeft:'auto'},
 driver:{gap:5,paddingVertical:7},driverHead:{flexDirection:'row',justifyContent:'space-between'},driverLabel:{color:ui.colors.text2,fontSize:10,fontWeight:'700'},driverValue:{color:ui.colors.text,fontSize:10,fontWeight:'900'},
 constraintRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10,borderBottomWidth:1,borderBottomColor:ui.colors.lineSoft},constraintTitle:{color:ui.colors.text,fontSize:10,fontWeight:'800'},constraintDetail:{color:ui.colors.text3,fontSize:8,marginTop:2},constraintRight:{width:125,alignItems:'flex-end',gap:7},
 evidenceRow:{flexDirection:'row',alignItems:'flex-start',gap:9,minHeight:62},evidenceLine:{position:'absolute',left:10,top:22,bottom:-8,width:1},evidenceIcon:{width:20,height:20,borderRadius:10,borderWidth:1,alignItems:'center',justifyContent:'center',zIndex:2},evidenceTitle:{color:ui.colors.text,fontSize:10,fontWeight:'900'},evidenceSource:{color:ui.colors.text3,fontSize:8,marginTop:2},evidenceHash:{color:ui.colors.cyan,fontSize:8,fontFamily:'monospace',marginTop:2},
 assumption:{paddingVertical:11,borderBottomWidth:1,borderBottomColor:ui.colors.lineSoft},assumptionLabel:{color:ui.colors.text2,fontSize:10,fontWeight:'800',flex:1},assumptionValue:{color:ui.colors.text,fontSize:10,fontWeight:'900'},assumptionMeta:{flexDirection:'row',justifyContent:'space-between',marginTop:4},assumptionRange:{color:ui.colors.text3,fontSize:8},assumptionImpact:{color:ui.colors.violet,fontSize:8,fontWeight:'900'},assumptionOpen:{marginTop:8,gap:6},assumptionOpenText:{color:ui.colors.text3,fontSize:9,lineHeight:14},
 waterfall:{height:180,flexDirection:'row',alignItems:'flex-end',gap:8},waterCol:{flex:1,height:'100%',justifyContent:'flex-end',alignItems:'center',gap:5},waterTrack:{height:120,width:'65%',backgroundColor:'#0B1D2C',borderRadius:7,justifyContent:'flex-end',overflow:'hidden'},waterBar:{width:'100%',borderRadius:7},waterLabel:{color:ui.colors.text3,fontSize:7,textAlign:'center'},waterValue:{color:ui.colors.text2,fontSize:8,fontWeight:'900'},
 trust:{flexDirection:'row',alignItems:'center',gap:10},trustIcon:{width:25,height:25,borderRadius:8,alignItems:'center',justifyContent:'center'},trustTitle:{color:ui.colors.text,fontSize:11,fontWeight:'900'},trustDetail:{color:ui.colors.text3,fontSize:9,lineHeight:14,marginTop:2},report:{gap:10},reportKpi:{flexDirection:'row',gap:24,marginTop:2},reportValue:{color:ui.colors.cyan,fontSize:24,fontWeight:'900',marginTop:3},reportKpiValue:{color:ui.colors.text,fontSize:16,fontWeight:'900',marginTop:3},miniSpark:{flex:1,minWidth:180},miniValue:{color:ui.colors.text,fontSize:19,fontWeight:'900'},miniTrend:{fontSize:9,fontWeight:'900',marginLeft:'auto'},pagination:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12},pageText:{color:ui.colors.text3,fontSize:10,fontWeight:'800'},filterBar:{flexDirection:'row',gap:6,flexWrap:'wrap'},filter:{paddingHorizontal:10,paddingVertical:7,borderRadius:10,borderWidth:1},filterText:{fontSize:9,fontWeight:'900'},gauge:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',minHeight:140},gaugeScore:{color:ui.colors.text,fontSize:35,fontWeight:'900',marginTop:3},gaugeCaption:{color:ui.colors.text3,fontSize:8,maxWidth:160},gaugeRing:{height:82,width:82,borderRadius:41,borderWidth:10,borderColor:'#122B3D',overflow:'hidden',justifyContent:'flex-end'},gaugeArc:{width:'100%',borderRadius:30}
});
